# Generated by Django 5.2.7 on 2026-09-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_id_alter_test_id_alter_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
